using System.Collections.Generic;
using System.Linq;
using RuinRail.EditorTools.Production;
using UnityEditor;
using UnityEngine;

namespace RuinRail.EditorTools.ArtGen
{
    /// <summary>
    /// Writes an originality attestation for every generated asset into production/asset_provenance.json.
    ///
    /// art/107 section 6 requires provenance before a role may claim final status, and the pipeline validator enforces
    /// it. The records here describe the assets accurately: they are **procedurally generated** by the project's own
    /// art-generation code from the palettes and design profiles in FINAL_ART_PRODUCTION_SPEC — original project work
    /// with no third-party source, but authored by algorithm rather than by hand, which a reviewer deserves to know.
    ///
    /// Nothing here asserts that the art is good. Quality remains a human judgment (art/107 section 5).
    /// </summary>
    public static class ProvenanceRecorder
    {
        public const string Author = "RUINRAIL procedural art pipeline (Assets/Game/Scripts/Editor/ArtGen)";
        public const string License = "project-owned";

        /// <summary>The provenance sentence per category, naming the generator and the spec section it implements.</summary>
        private static string ProvenanceFor(string category) => category switch
        {
            "Character source sprites" =>
                "Procedurally generated by CharacterSpriteFactory from the design profile in CharacterCatalog; construction, proportions and palette follow FINAL_ART_PRODUCTION_SPEC sections 4, 6-9.",
            "Character animation clip roles" =>
                "Clips assembled by AnimationSetBuilder from the generated directional sheet; frame counts and rates follow spec section 5.",
            "Weapon sprites" =>
                "Procedurally generated by WeaponFactory from the per-weapon design profile in spec section 11; authored +X for the existing WeaponPivot.",
            "Item icons" =>
                "Procedurally generated by IconFactory; weapon icons are the generated world sprite re-projected, other families use the object metaphors in spec section 12.",
            "Biome tiles" =>
                "Procedurally generated by TileFactory from the biome material and screen-balance rules in spec sections 13-15.",
            "Biome props and dressing" =>
                "Procedurally generated by BiomeDressingFactory from each biome's named prop list in spec sections 13-15.",
            "Biome lighting" =>
                "Ambient tint authored from spec section 20, constrained by the runtime readability floor.",
            "World objects and base presentation" =>
                "Procedurally generated by WorldObjectFactory from the object and station descriptions in spec sections 16-17.",
            "UI skin" =>
                "Procedurally generated by UiFactory and PixelFontFactory from the UI system in spec section 18; the pixel typeface is original glyph-by-glyph bitmap work.",
            "VFX" =>
                "Procedurally generated by VfxFactory from the effect and telegraph rules in spec section 19.",
            "Projectile visuals" =>
                "Procedurally generated by ProjectileFactory: original RUINRAIL pixel projectile sprites per weapon family / hostile attack, authored +X with a head pivot.",
            "SFX" =>
                "Synthesised by GameAudioFactory from original oscillator/noise/envelope construction; no sample library or third-party recording.",
            "Music" =>
                "Synthesised by GameAudioFactory as an original loopable arrangement in a fixed key per biome; no sample library.",
            "Stingers" =>
                "Synthesised by GameAudioFactory as original short motifs; no sample library.",
            "Ambience" =>
                "Synthesised by GameAudioFactory as original seamless noise/tone beds per biome; no sample library.",
            "Network prefab" =>
                "Authored by NetworkPlayerPrefabAuthoring from the existing PlayerEntityBuilder composition plus NGO components.",
            _ => "Procedurally generated by the RUINRAIL art pipeline."
        };

        [MenuItem("RuinRail/Art/Record Asset Provenance")]
        public static void RecordMenu() => Debug.Log($"Recorded provenance for {Record()} roles.");

        public static int Record()
        {
            var manifest = CompletionAssetManifest.Generate();
            var entries = new List<AssetProvenanceRegistry.Entry>();

            // Keep any hand-written record a human added; only fill in what the pipeline produced.
            var existing = AssetProvenanceRegistry.Load()
                .ToDictionary(e => e.roleId, e => e, System.StringComparer.Ordinal);

            // One entry per role id, not per manifest row: a character appears twice (source sheet and animation set)
            // under the same id, and the attestation check looks the role up by id, so a second entry would be a
            // duplicate rather than extra information.
            var written = new HashSet<string>(System.StringComparer.Ordinal);

            foreach (var role in manifest.Roles)
            {
                if (role.Status != CompletionAssetManifest.Integrated) continue;
                if (!written.Add(role.RoleId)) continue;

                if (existing.TryGetValue(role.RoleId, out var kept))
                {
                    entries.Add(kept);
                    continue;
                }

                entries.Add(new AssetProvenanceRegistry.Entry
                {
                    roleId = role.RoleId,
                    sourcePath = role.ExpectedSourcePath,
                    author = Author,
                    provenance = ProvenanceFor(role.Category),
                    license = License,
                    derivedFromReferenceGame = false,
                    // Deliberately left empty: approval is a human act at the TASK 152/165/176 gates, and the
                    // pipeline must never sign its own work off as reviewed.
                    approvedBy = string.Empty
                });
            }

            AssetProvenanceRegistry.Save(entries);
            return entries.Count;
        }
    }
}
