using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using RuinRail.Audio;
using RuinRail.Core;
using RuinRail.Gameplay.Enemies;
using RuinRail.Gameplay.Enemies.Attacks;
using RuinRail.Gameplay.Enemies.Bosses;
using RuinRail.Gameplay.Enemies.Elites;
using RuinRail.Gameplay.Events;
using RuinRail.Gameplay.Items;
using RuinRail.Gameplay.Items.Consumables;
using RuinRail.Presentation.Animation;
using UnityEditor;
using UnityEngine;

namespace RuinRail.EditorTools.Production
{
    /// <summary>
    /// TASK 149 completion manifest (production/134): enumerates every final asset role from the repository itself —
    /// definitions, code role ids and existing assets — and reconciles the totals against the TASK-148 baselines in
    /// production/135. It never keeps a count list of its own: every number is derived, and a delta is reported with
    /// the code/data source that produced it. Audit only; it changes no gameplay data.
    /// </summary>
    public static class CompletionAssetManifest
    {
        public const string ReportPath = "TestResults/completion_asset_manifest.md";
        /// <summary>The generated pixel font, which replaces the builtin LegacyRuntime.ttf in the release path.</summary>
        public const string PixelFontPath = "Assets/Game/Resources/Fonts/ruinrail_pixel.fontsettings";
        /// <summary>production/134 status vocabulary.</summary>
        public const string Missing = "MISSING";
        public const string Placeholder = "PLACEHOLDER";
        public const string Integrated = "INTEGRATED";

        public sealed class Role
        {
            public string Category;
            public string RoleId;
            public string Owner;
            public string AssetType;
            public string Spec;
            public string Status;
            /// <summary>Where the role's asset currently resolves from, if anywhere.</summary>
            public string SourcePath = "—";
            /// <summary>TASK 151 convention path a final asset must land at (AssetNamingConvention).</summary>
            public string ExpectedSourcePath = string.Empty;
            /// <summary>The existing runtime object that binds the asset, so a replacement changes no gameplay id.</summary>
            public string BindingPoint = string.Empty;
        }

        public sealed class Reconciliation
        {
            public string Item;
            public int Baseline;
            public int Current;
            public string Source;
            /// <summary>Set only for a delta TASK 149 verified against the repository and explained. Empty means "must match".</summary>
            public string ExplainedDelta = string.Empty;
            public bool Match => Baseline == Current;
            public bool Explained => ExplainedDelta.Length > 0;
            public string Result => Match ? "EXACT" : Explained ? "DELTA (explained)" : "DELTA (unexplained)";
        }

        public sealed class Report
        {
            public readonly List<Role> Roles = new();
            public readonly List<Reconciliation> Reconciliations = new();
            public readonly List<string> LiveServiceBlockers = new();
            public readonly List<string> EngineeringBlockers = new();
            public readonly List<string> HumanGates = new();
            public string ReleasePlatformScope = string.Empty;

            public int Count(string status) => Roles.Count(r => r.Status == status);
            /// <summary>True when nothing drifted silently: every count either matches the baseline or carries a verified explanation.</summary>
            public bool AllReconciled => Reconciliations.All(r => r.Match || r.Explained);
            public IEnumerable<string> Categories => Roles.Select(r => r.Category).Distinct();

            public string ToMarkdown()
            {
                var sb = new StringBuilder();
                sb.AppendLine("# RUINRAIL Completion Asset Manifest (TASK 149)");
                sb.AppendLine();
                sb.AppendLine("> Generated by `RuinRail/Production/Generate Completion Asset Manifest`. Do not hand-edit: regenerate.");
                sb.AppendLine("> Status vocabulary: production/134. Runner rules: production/133. Art direction: art/106.");
                sb.AppendLine();
                sb.AppendLine($"Total final asset roles: **{Roles.Count}** — {Count(Integrated)} INTEGRATED, {Count(Placeholder)} PLACEHOLDER, {Count(Missing)} MISSING.");
                sb.AppendLine($"TASK-148 baseline reconciliation: **{(AllReconciled ? "RECONCILED" : "UNEXPLAINED DRIFT")}** — {Reconciliations.Count(r => r.Match)}/{Reconciliations.Count} counts match exactly, {Reconciliations.Count(r => !r.Match)} explained delta(s).");
                sb.AppendLine();

                sb.AppendLine("## Baseline Reconciliation (production/135)");
                sb.AppendLine();
                sb.AppendLine("| Item | TASK-148 baseline | Current | Source of truth | Result |");
                sb.AppendLine("|---|---:|---:|---|---|");
                foreach (var r in Reconciliations)
                {
                    sb.AppendLine($"| {r.Item} | {r.Baseline} | {r.Current} | {r.Source} | {r.Result} |");
                }

                foreach (var r in Reconciliations.Where(x => !x.Match))
                {
                    sb.AppendLine();
                    sb.AppendLine($"**Delta — {r.Item}:** {r.ExplainedDelta}");
                }

                sb.AppendLine();
                sb.AppendLine("## Asset Roles by Category");
                foreach (var category in Categories)
                {
                    var rows = Roles.Where(r => r.Category == category).ToList();
                    sb.AppendLine();
                    sb.AppendLine($"### {category} — {rows.Count} roles ({rows.Count(r => r.Status == Integrated)} INTEGRATED / {rows.Count(r => r.Status == Placeholder)} PLACEHOLDER / {rows.Count(r => r.Status == Missing)} MISSING)");
                    sb.AppendLine();
                    sb.AppendLine("| Role id | Runtime owner | Asset type | Required spec | Expected source path | Binding point | Current source | Status |");
                    sb.AppendLine("|---|---|---|---|---|---|---|---|");
                    foreach (var row in rows)
                    {
                        var expected = row.ExpectedSourcePath.Length > 0 ? row.ExpectedSourcePath : "—";
                        var binding = row.BindingPoint.Length > 0 ? row.BindingPoint : "—";
                        sb.AppendLine($"| {row.RoleId} | {row.Owner} | {row.AssetType} | {row.Spec} | {expected} | {binding} | {row.SourcePath} | {row.Status} |");
                    }
                }

                sb.AppendLine();
                sb.AppendLine("## Live Online Service Blockers");
                sb.AppendLine();
                foreach (var b in LiveServiceBlockers) sb.AppendLine($"- {b}");

                sb.AppendLine();
                sb.AppendLine("## Engineering / Release Blockers");
                sb.AppendLine();
                foreach (var b in EngineeringBlockers) sb.AppendLine($"- {b}");

                sb.AppendLine();
                sb.AppendLine("## Human / External Approval Still Required");
                sb.AppendLine();
                foreach (var g in HumanGates) sb.AppendLine($"- {g}");

                sb.AppendLine();
                sb.AppendLine("## Release Platform Scope");
                sb.AppendLine();
                sb.AppendLine(ReleasePlatformScope);
                return sb.ToString();
            }
        }

        [MenuItem("RuinRail/Production/Generate Completion Asset Manifest")]
        public static void GenerateMenu() => Debug.Log(WriteReport().ToMarkdown());

        public static Report WriteReport()
        {
            var report = Generate();
            Directory.CreateDirectory(Path.GetDirectoryName(ReportPath) ?? "production");
            File.WriteAllText(ReportPath, report.ToMarkdown());
            return report;
        }

        public static Report Generate()
        {
            var r = new Report();
            AddCharacterRoles(r);
            AddWeaponRoles(r);
            AddItemIconRoles(r);
            AddEnvironmentRoles(r);
            AddWorldObjectRoles(r);
            AddUiRoles(r);
            AddVfxRoles(r);
            AddAudioRoles(r);
            AddNetworkPrefabRoles(r);
            ApplyNamingConvention(r);
            AddReconciliations(r);
            AddBlockers(r);
            return r;
        }

        /// <summary>TASK 151: stamp each role with where its final asset belongs and what already binds it.</summary>
        private static void ApplyNamingConvention(Report r)
        {
            foreach (var role in r.Roles)
            {
                var placement = AssetNamingConvention.For(role.Category, role.RoleId);
                role.ExpectedSourcePath = placement.ExpectedSourcePath;
                role.BindingPoint = placement.BindingPoint;
            }
        }

        // ---- status resolution ----


        /// <summary>
        /// A role is INTEGRATED when its asset actually resolves at the convention path, PLACEHOLDER when only dev art
        /// stands in, and MISSING otherwise. Resolving this from the filesystem rather than hard-coding it is what lets
        /// the batch gates and the final audit tell the truth as art lands.
        /// </summary>
        private static string StatusOfSprite(string assetPath) =>
            AssetDatabase.LoadAssetAtPath<Sprite>(assetPath) != null ? Integrated : Missing;

        /// <summary>Lighting is final once its tint has left neutral white for the biome's authored look.</summary>
        private static string LightingStatus(Biome biome)
        {
            var profile = AssetDatabase.LoadAssetAtPath<RuinRail.Presentation.BiomeLightingProfile>(
                $"Assets/Game/ScriptableObjects/Presentation/Lighting_{biome}.asset");
            if (profile == null) return Missing;

            var c = profile.GlobalLightColor;
            var neutral = Mathf.Approximately(c.r, 1f) && Mathf.Approximately(c.g, 1f) && Mathf.Approximately(c.b, 1f);
            return neutral ? Placeholder : Integrated;
        }

        /// <summary>The music catalog asset, loaded once per manifest generation.</summary>


        private static MusicCatalog MusicCatalogAsset =>


            AssetDatabase.LoadAssetAtPath<MusicCatalog>("Assets/Game/ScriptableObjects/Audio/MusicCatalog.asset");



        /// <summary>Ammo icons are keyed by the AmmoItemDefinition that carries that ammo type.</summary>
        private static string AmmoIconStatus(AmmoType ammo)
        {
            foreach (var definition in LoadAll<AmmoItemDefinition>())
                if (definition.AmmoType == ammo) return definition.HasIcon ? Integrated : Missing;
            return Missing;
        }

        /// <summary>A biome tile is final once a tile asset exists outside the shared placeholder folder.</summary>
        private static (string Status, string Source) TileStatus(Biome biome, string role)
        {
            var finalPath = $"Assets/Game/Art/Tiles/{biome}/{biome.ToString().ToLowerInvariant()}_{role}.asset";
            if (AssetDatabase.LoadAssetAtPath<UnityEngine.Tilemaps.TileBase>(finalPath) != null)
                return (Integrated, finalPath);

            var placeholder = $"Assets/Game/Art/Tiles/_Placeholder/Placeholder_{ToPascal(role)}.asset";
            return string.IsNullOrEmpty(AssetDatabase.AssetPathToGUID(placeholder))
                ? (Missing, "—")
                : (Placeholder, placeholder + " (shared by all 3 biomes)");
        }

        // ---- Characters and animation ----
        private static void AddCharacterRoles(Report r)
        {
            var sets = LoadAll<CharacterAnimationSet>();

            void Actor(string actorId, string kind, string[] keys, string canvas)
            {
                var set = sets.FirstOrDefault(s => string.Equals(s.ActorId, actorId, StringComparison.OrdinalIgnoreCase));
                var required = keys.Length * AnimationRules.AllFacings.Length;
                var missing = set != null ? set.Missing(keys).Count : required;
                r.Roles.Add(new Role
                {
                    Category = "Character source sprites",
                    RoleId = actorId,
                    Owner = kind == "Player" ? "PlayerAnimationDriver" : "EnemyAnimationDriver",
                    AssetType = "Directional sprite sheet",
                    Spec = $"{kind}, 8 facings, art/106 section 3 canvas {canvas}, 32 PPU",
                    Status = set != null && missing == 0 ? Integrated : Missing
                });
                r.Roles.Add(new Role
                {
                    Category = "Character animation clip roles",
                    RoleId = actorId,
                    Owner = "CharacterAnimationSet",
                    AssetType = "SpriteAnimationClip set",
                    Spec = $"{string.Join("/", keys)} x 8 facings = {required} clip roles ({missing} outstanding), {AnimationRules.MinFps}-{AnimationRules.MaxFps} fps (art/103)",
                    Status = set == null ? Missing : missing == 0 ? Integrated : Placeholder,
                    SourcePath = set != null ? AssetDatabase.GetAssetPath(set) : "—"
                });
            }

            Actor(AnimationAssetAudit.PlayerActorId, "Player", AnimationRules.PlayerClipKeys, "~32x48 px");
            foreach (var e in LoadAll<EnemyDefinition>()) Actor(e.Id, "Enemy", AnimationRules.EnemyClipKeys, "16-64 px by archetype");
            foreach (var e in LoadAll<EliteDefinition>()) Actor(e.Id, "Elite", AnimationRules.EnemyClipKeys, "~48-64+ px");
            foreach (var b in LoadAll<BossDefinition>()) Actor(b.Id, "Boss", AnimationRules.EnemyClipKeys, "~64-128 px");
        }

        // ---- Weapons ----

        private static void AddWeaponRoles(Report r)
        {
            foreach (var w in LoadAll<WeaponDefinition>())
            {
                r.Roles.Add(new Role
                {
                    Category = "Weapon sprites",
                    RoleId = w.Id,
                    Owner = "WeaponVisualDriver (360 degree WeaponPivot)",
                    AssetType = "World/equipped sprite",
                    Spec = $"{w.WeaponClass} class silhouette (art/106 section 5), 32 PPU",
                    Status = StatusOfSprite($"Assets/Game/Art/Weapons/{w.Id}.png")
                });
            }
        }

        // ---- Item family icons ----

        private static void AddItemIconRoles(Report r)
        {
            void Icons<T>(string family) where T : ItemDefinition
            {
                foreach (var item in LoadAll<T>())
                {
                    r.Roles.Add(new Role
                    {
                        Category = "Item icons",
                        RoleId = item.Id,
                        Owner = "InventoryView / DungeonHudView",
                        AssetType = "UI icon",
                        Spec = $"{family} icon, rarity-frame compatible (art/106 section 9)",
                        Status = item.HasIcon ? Integrated : Missing
                    });
                }
            }

            Icons<WeaponDefinition>("Weapon");
            Icons<ArmorDefinition>("Armor");
            Icons<AccessoryDefinition>("Accessory");
            Icons<ConsumableDefinition>("Consumable");
            foreach (var ammo in Enum.GetValues(typeof(AmmoType)).Cast<AmmoType>())
            {
                r.Roles.Add(new Role
                {
                    Category = "Item icons",
                    RoleId = "ammo." + ammo,
                    Owner = "DungeonHudView / InventoryView",
                    AssetType = "UI icon",
                    Spec = "Ammo category icon (art/106 section 9)",
                    Status = AmmoIconStatus(ammo)
                });
            }
        }

        // ---- Environment ----

        /// <summary>The tile categories the room baker authors per biome; one placeholder set is shared by all three.</summary>
        public static readonly string[] TileCategories = { "floor", "floor_detail", "wall", "obstacle", "hazard" };

        /// <summary>art/106 section 7 per-biome packages required beyond the five logic tile categories.</summary>
        public static readonly string[] PropCategories = { "props", "doors", "rail_transit", "decals", "foreground", "environment_vfx" };

        private static void AddEnvironmentRoles(Report r)
        {
            foreach (var biome in Enum.GetValues(typeof(Biome)).Cast<Biome>())
            {
                foreach (var tile in TileCategories)
                {
                    var (status, source) = TileStatus(biome, tile);
                    r.Roles.Add(new Role
                    {
                        Category = "Biome tiles",
                        RoleId = $"{biome}.tile.{tile}",
                        Owner = "RoomPrefabBaker / Tilemap",
                        AssetType = "Tile + 32x32 sprite",
                        Spec = "32x32 px on the approved grid (art/101), biome identity per art/106 section 7",
                        Status = status,
                        SourcePath = source
                    });
                }

                foreach (var prop in PropCategories)
                {
                    r.Roles.Add(new Role
                    {
                        Category = "Biome props and dressing",
                        RoleId = $"{biome}.{prop}",
                        Owner = "Room prefabs (63)",
                        AssetType = "Sprite package",
                        Spec = "art/106 section 7 biome mood package",
                        Status = StatusOfSprite($"Assets/Game/Art/Props/{biome}/{prop}/{biome.ToString().ToLowerInvariant()}_{prop}.png")
                    });
                }

                r.Roles.Add(new Role
                {
                    Category = "Biome lighting",
                    RoleId = $"{biome}.lighting",
                    Owner = "BiomeLightingProfile",
                    AssetType = "Lighting profile",
                    Spec = "art/106 section 11 distinct biome look; authored ambient tint per biome",
                    Status = LightingStatus(biome),
                    SourcePath = $"Assets/Game/ScriptableObjects/Presentation/Lighting_{biome}.asset"
                });
            }
        }

        // ---- World objects ----

        /// <summary>Existing runtime world objects that need final presentation. No new gameplay objects.</summary>
        public static readonly (string Role, string Owner)[] WorldObjects =
        {
            ("world.supply_chest", "SupplyChest"),
            ("world.item_pickup", "WorldItemPickup"),
            ("world.coin_pickup", "CoinPickup"),
            ("world.dungeon_merchant", "DungeonMerchantInteractable"),
            ("world.boss_cache_gate", "BossCacheGate"),
            ("world.door_socket", "DoorSocket / RoomDoorLock"),
            ("world.room_hazard", "RoomHazard"),
            ("world.transit_car", "ExpeditionScene transit"),
            ("base.storage", "Storage"),
            ("base.trader", "TraderService"),
            ("base.workshop", "WorkshopService"),
            ("base.character_station", "CharacterStation")
        };

        private static void AddWorldObjectRoles(Report r)
        {
            foreach (var (role, owner) in WorldObjects)
            {
                r.Roles.Add(new Role
                {
                    Category = "World objects and base presentation",
                    RoleId = role,
                    Owner = owner,
                    AssetType = "Sprite / prefab presentation",
                    Spec = "art/106 sections 7-8",
                    Status = StatusOfSprite("Assets/Game/Art/World/" + role.Replace('.', '_') + ".png")
                });
            }

            foreach (var kind in Enum.GetNames(typeof(DungeonEventKind)))
            {
                r.Roles.Add(new Role
                {
                    Category = "World objects and base presentation",
                    RoleId = "event." + kind,
                    Owner = "DungeonEventInteractable",
                    AssetType = "Sprite / prefab presentation",
                    Spec = "art/106 section 7 readable interactable",
                    Status = StatusOfSprite("Assets/Game/Art/World/event_" + kind + ".png")
                });
            }
        }

        // ---- UI ----

        /// <summary>UI-only roles beyond the item-family icons (art/106 section 9).</summary>
        public static readonly string[] UiRoles =
        {
            "ui.panel_frame", "ui.button", "ui.button_focus", "ui.inventory_slot",
            "ui.rarity_frame.Common", "ui.rarity_frame.Uncommon", "ui.rarity_frame.Rare", "ui.rarity_frame.Epic", "ui.rarity_frame.Legendary",
            "ui.bar.hp", "ui.bar.xp", "ui.glyphs.keyboard", "ui.glyphs.controller", "ui.dash_icon",
            "ui.coin_icon", "ui.vignette_low_hp", "ui.enemy_icon",
            "ui.mainmenu_background", "ui.shelter_stations"
        };

        private static void AddUiRoles(Report r)
        {
            foreach (var role in UiRoles)
            {
                r.Roles.Add(new Role
                {
                    Category = "UI skin",
                    RoleId = role,
                    Owner = "UiKit / views",
                    AssetType = "UI sprite",
                    Spec = "art/106 section 9 utilitarian shelter/field equipment; grey rectangles are the current placeholder",
                    Status = StatusOfSprite("Assets/Game/Art/UI/" + role.Replace('.', '_') + ".png")
                });
            }

            r.Roles.Add(new Role
            {
                Category = "UI skin",
                RoleId = "ui.font.pixel",
                Owner = "UiKit.Font()",
                AssetType = "Font + licensing metadata",
                Spec = "art/106 section 9 readable pixel face; UiKit currently returns the builtin LegacyRuntime.ttf",
                Status = AssetDatabase.LoadAssetAtPath<Font>(PixelFontPath) != null ? Integrated : Placeholder,
                SourcePath = AssetDatabase.LoadAssetAtPath<Font>(PixelFontPath) != null ? PixelFontPath : "builtin LegacyRuntime.ttf"
            });
        }

        // ---- VFX ----

        /// <summary>Effect kinds CombatFeedback spawns, in addition to the telegraph shapes TelegraphIndicator draws.</summary>
        public static readonly string[] VfxKinds = { "muzzle", "impact", "explosion", "melee", "stagger", "heal", "status", "loot_glow" };

        private static void AddVfxRoles(Report r)
        {
            foreach (var kind in VfxKinds)
            {
                r.Roles.Add(new Role
                {
                    Category = "VFX",
                    RoleId = "vfx." + kind,
                    Owner = "CombatFeedback / EffectPool",
                    AssetType = "Effect sprite (or frame strip)",
                    Spec = "art/106 section 10 short, layered, never hides hazards; the current pool sprite is a white square",
                    Status = StatusOfSprite("Assets/Game/Art/Vfx/vfx_" + kind + ".png")
                });
            }

            foreach (var spec in RuinRail.EditorTools.ArtGen.ProjectileFactory.Specs())
            {
                r.Roles.Add(new Role
                {
                    Category = "Projectile visuals",
                    RoleId = "vfx." + spec.Id,
                    Owner = "ProjectileVisual (pooled projectile presentation) via ProjectileVisualCatalog",
                    AssetType = "In-flight projectile sprite (or 2-frame strip)",
                    Spec = "Projectile visuals pass: " + spec.Description + "; authored +X, pivot at the head, readable at 640x360",
                    Status = StatusOfSprite(RuinRail.EditorTools.ArtGen.ProjectileArtIntegration.SheetPath(spec.Id))
                });
            }

            foreach (var motion in Enum.GetNames(typeof(AttackMotion)))
            {
                r.Roles.Add(new Role
                {
                    Category = "VFX",
                    RoleId = "vfx.telegraph." + motion.ToLowerInvariant(),
                    Owner = "TelegraphIndicator",
                    AssetType = "Telegraph marker sprite",
                    Spec = "art/106 section 2 readability; one telegraph pool kind scaled per AttackMotion shape",
                    Status = StatusOfSprite("Assets/Game/Art/Vfx/vfx_telegraph_" + motion.ToLowerInvariant() + ".png")
                });
            }
        }

        // ---- Audio ----

        private static void AddAudioRoles(Report r)
        {
            var catalog = AssetDatabase.LoadAssetAtPath<AudioEventCatalog>(AudioAssetAudit.CatalogPath);
            foreach (var (id, bus, _) in AudioEventIds.Required)
            {
                var defined = catalog != null && catalog.TryGet(id, out var definition) && definition != null;
                var hasClips = defined && catalog.TryGet(id, out var d) && d.HasClips;
                r.Roles.Add(new Role
                {
                    Category = "SFX",
                    RoleId = id,
                    Owner = $"AudioService / GameplayAudioBinder ({bus} bus)",
                    AssetType = "AudioClip",
                    Spec = defined ? "art/105 bus routing; the event definition exists, the clip list is empty" : "art/105 bus routing; no event definition",
                    Status = hasClips ? Integrated : Missing,
                    SourcePath = defined ? AudioAssetAudit.CatalogPath : "—"
                });
            }

            foreach (var role in Enum.GetValues(typeof(MusicRole)).Cast<MusicRole>())
            {
                r.Roles.Add(new Role
                {
                    Category = "Music",
                    RoleId = "music." + role,
                    Owner = "MusicDirector / MusicCatalog",
                    AssetType = "AudioClip (full track)",
                    Spec = MusicStateResolver.DisplayName(role),
                    Status = MusicCatalogAsset != null && MusicCatalogAsset.TrackFor(role) != null ? Integrated : Missing
                });
            }

            foreach (var stinger in Enum.GetValues(typeof(StingerRole)).Cast<StingerRole>())
            {
                r.Roles.Add(new Role
                {
                    Category = "Stingers",
                    RoleId = "stinger." + stinger,
                    Owner = "MusicDirector",
                    AssetType = "AudioClip (stinger)",
                    Spec = "art/105 stinger; not counted as a track",
                    Status = MusicCatalogAsset != null && MusicCatalogAsset.StingerFor(stinger) != null ? Integrated : Missing
                });
            }

            foreach (var biome in Enum.GetValues(typeof(Biome)).Cast<Biome>())
            {
                r.Roles.Add(new Role
                {
                    Category = "Ambience",
                    RoleId = "ambience." + biome,
                    Owner = "MusicDirector ambience bus",
                    AssetType = "AudioClip (loop)",
                    Spec = MusicStateResolver.AmbienceDescription(biome),
                    Status = MusicCatalogAsset != null && MusicCatalogAsset.AmbienceFor(biome) != null ? Integrated : Missing
                });
            }
        }

        // ---- Network prefab ----

        private static void AddNetworkPrefabRoles(Report r)
        {
            r.Roles.Add(new Role
            {
                Category = "Network prefab",
                RoleId = "network.player_prefab",
                Owner = "NgoPlayerEntityFactory / DefaultNetworkPrefabs.asset",
                AssetType = "NetworkObject prefab",
                Spec = "TASK 180: final player prefab carrying the presentation components the release build needs",
                Status = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Game/Prefabs/Network/PlayerNetworkEntity.prefab") != null ? Integrated : Missing,
                SourcePath = "Assets/DefaultNetworkPrefabs.asset"
            });
        }

        // ---- Reconciliation against production/135 ----

        private static void AddReconciliations(Report r)
        {
            int RolesIn(string category) => r.Roles.Count(x => x.Category == category);

            void Check(string item, int baseline, int current, string source, string explainedDelta = "") =>
                r.Reconciliations.Add(new Reconciliation { Item = item, Baseline = baseline, Current = current, Source = source, ExplainedDelta = explainedDelta });

            var sets = RolesIn("Character animation clip roles");
            var perSet = AnimationRules.EnemyClipKeys.Length * AnimationRules.AllFacings.Length;
            Check("Animation sets (player + 9 + 6 + 6)", 22, sets, "EnemyDefinition/EliteDefinition/BossDefinition assets plus the player");
            Check("Clip roles per set", 48, perSet, "AnimationRules.EnemyClipKeys x AllFacings");
            Check("Total animation clip roles", 1056, sets * perSet, "22 sets x 48");
            Check("Weapon sprite roles", 33, RolesIn("Weapon sprites"), "WeaponDefinition assets");
            Check("Item-family icon roles", 72, RolesIn("Item icons"), "Weapon+Armor+Accessory+Consumable definitions plus AmmoType values");
            Check("SFX event ids", 53, AudioEventIds.Required.Count, "RuinRail.Audio.AudioEventIds.Required");
            Check("Music roles", 11, Enum.GetValues(typeof(MusicRole)).Length, "RuinRail.Audio.MusicRole");
            Check("Stinger roles", 6, Enum.GetValues(typeof(StingerRole)).Length, "RuinRail.Audio.StingerRole");
            Check("Ambience roles", 3, Enum.GetValues(typeof(Biome)).Length, "RuinRail.Core.Biome");
            Check("Biome art packages", 3, Enum.GetValues(typeof(Biome)).Length, "RuinRail.Core.Biome");
            Check("VFX roles", 12, RolesIn("VFX"), "CombatFeedback effect kinds plus AttackMotion telegraph shapes",
                "production/135 enumerated four telegraph shapes (zone, dash, projectile, slam) but RuinRail.Gameplay.Enemies.Attacks.AttackMotion " +
                "has five values: TelegraphIndicator.ShapeFor also draws the Stationary case (a radius in front of the attacker) through its default branch. " +
                "The current role count is 8 CombatFeedback kinds + 5 AttackMotion shapes = 13. No content was added; the baseline list was short by one. " +
                "production/135 carries the matching correction note.");
            Check("PROTOTYPE markers", 0, PrototypeMarkerCount(), "PROTOTYPE scan over Assets/Game/Scripts and ScriptableObjects, excluding Tests (TASK 179 dispositioned 34 of 35; the last, biome lighting, resolved once the biome art existed)");
            // TASK 177 migrated all 12 calls to the supported ContactFilter2D overloads, so the baseline is now zero.
            // The TASK-148 figures (12 calls / 7 files) are recorded in production/135 as resolved, not as drift.
            Check("Deprecated Physics2D NonAlloc calls", 0, NonAllocCallCount(), "Physics2D NonAlloc scan over Assets/Game/Scripts (TASK 177 migrated 12 -> 0)");
            Check("Files containing NonAlloc calls", 0, NonAllocFileCount(), "Physics2D NonAlloc scan over Assets/Game/Scripts (TASK 177 migrated 7 -> 0)");
        }

        /// <summary>
        /// Counts PROTOTYPE markers the way the TASK-148 baseline did: runtime scripts and authored data only.
        /// Tests and editor tooling are excluded — they hold no gameplay tunable, and this file itself names the
        /// marker several times, which would otherwise inflate its own count.
        /// </summary>
        public static int PrototypeMarkerCount() =>
            CountLines("PROTOTYPE", new[] { "Assets/Game/Scripts", "Assets/Game/ScriptableObjects" }, new[] { ".cs", ".asset" });

        public static int NonAllocCallCount() =>
            CountLines("Physics2D.", new[] { "Assets/Game/Scripts" }, new[] { ".cs" }, "NonAlloc");

        public static int NonAllocFileCount() =>
            SourceFiles(new[] { "Assets/Game/Scripts" }, new[] { ".cs" })
                .Count(f => File.ReadLines(f).Any(l => l.Contains("Physics2D.") && l.Contains("NonAlloc")));

        private static int CountLines(string needle, string[] roots, string[] extensions, string alsoOnLine = null) =>
            SourceFiles(roots, extensions)
                .SelectMany(File.ReadLines)
                .Count(line => line.Contains(needle) && (alsoOnLine == null || line.Contains(alsoOnLine)));

        /// <summary>Authored runtime sources: tests and editor tooling never hold a gameplay tunable or a shipped call site.</summary>
        private static IEnumerable<string> SourceFiles(string[] roots, string[] extensions) =>
            roots.Where(Directory.Exists)
                .SelectMany(root => Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))
                .Where(f => extensions.Contains(Path.GetExtension(f)))
                .Select(f => f.Replace('\\', '/'))
                .Where(f => !f.Contains("/Tests/") && !f.Contains("/Editor/"));

        // ---- Non-asset blockers ----

        private static void AddBlockers(Report r)
        {
            var prefabs = AssetDatabase.LoadAssetAtPath<Unity.Netcode.NetworkPrefabsList>("Assets/DefaultNetworkPrefabs.asset");
            var registered = prefabs != null ? prefabs.PrefabList.Count : 0;

            r.LiveServiceBlockers.Add($"DefaultNetworkPrefabs.asset registers {registered} network prefabs; NgoPlayerEntityFactory has no release player prefab (TASK 180).");
            r.LiveServiceBlockers.Add("GameApp composes FakeMultiplayerServices + FakeNetworkDriver; NetworkBootstrap can select UnityMultiplayerServices + NgoNetworkDriver, but the release boot path does not (TASK 180).");
            r.LiveServiceBlockers.Add("No Unity Gaming Services project id/link is configured in this repository, so live Sessions/Relay is NOT RUN (TASK 180-181).");
            r.LiveServiceBlockers.Add("The RUINRAIL_LIVE_SERVICES=1 live Sessions/Relay integration test is the one skipped EditMode test (TASK 181).");
            r.LiveServiceBlockers.Add("Two-built-client host/join over Relay with a real join code: NOT RUN (TASK 181). Mocks cannot satisfy it.");

            var nonAlloc = NonAllocCallCount();
            r.EngineeringBlockers.Add(nonAlloc == 0
                ? "Deprecated Physics2D NonAlloc calls: none (TASK 177 migrated all 12 to ContactFilter2D overloads). RESOLVED."
                : $"{nonAlloc} deprecated Physics2D NonAlloc calls across {NonAllocFileCount()} files raise CS0618 (TASK 177).");
            r.EngineeringBlockers.Add("GameApp.LoadScene calls SceneManager.LoadScene synchronously; no loading, transition or recoverable-error presentation exists (TASK 178).");
            r.EngineeringBlockers.Add(PrototypeMarkerCount() == 0 ? "PROTOTYPE markers: none. All 35 dispositioned (production/137); the last, biome lighting, was authored once the biome art existed. RESOLVED." : $"{PrototypeMarkerCount()} PROTOTYPE marker(s) still undispositioned.");
            r.EngineeringBlockers.Add("ItemDefinition carries no icon/sprite reference, so item art needs an icon seam before TASK 158/163 can integrate icons.");
            r.EngineeringBlockers.Add("Player-build profiling on the intended target hardware: NOT RUN (TASK 183).");

            r.HumanGates.Add("TASK 152 - approve the representative visual slice before bulk visual production.");
            r.HumanGates.Add("TASK 165 - approve the full visual content in an actual build.");
            r.HumanGates.Add("TASK 176 - approve sound, music and integrated presentation.");
            r.HumanGates.Add("TASK 179 - resolve every feel/design-dependent PROTOTYPE disposition.");
            r.HumanGates.Add("TASK 181 - real UGS linkage and real two-client Relay evidence.");
            r.HumanGates.Add("TASK 182 - human playtest sign-off on feel, readability and balance.");
            r.HumanGates.Add("TASK 183 - target-hardware profiling must actually run.");

            r.ReleasePlatformScope =
                "Proven: **Windows x64 standalone, non-development** (TASK 147/148 build plus built-player smoke). " +
                "No other platform has been built or validated in this repository, so no other platform is claimed as supported. " +
                "TASK 184 must state this scope truthfully rather than imply broader support.";
        }

        // ---- Helpers ----

        private static string ToPascal(string snake) =>
            string.Concat(snake.Split('_').Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));

        private static List<T> LoadAll<T>() where T : UnityEngine.Object =>
            AssetDatabase.FindAssets($"t:{typeof(T).Name}")
                .Select(g => AssetDatabase.LoadAssetAtPath<T>(AssetDatabase.GUIDToAssetPath(g)))
                .Where(a => a != null)
                .OrderBy(a => AssetDatabase.GetAssetPath(a), StringComparer.Ordinal)
                .ToList();
    }
}
